//! DefaultEventBus — Synchronous pub/sub with handler dispatch
//!
//! Design: Events are published to a queue. When drain() is called,
//! all pending events are dispatched to matching handlers.
//! This synchronous design fits the current Runtime event loop.

use crate::error::Result;
use crate::event_bus::traits::*;
use std::sync::Mutex;
use tracing::debug;

struct Subscription {
    id: String,
    pattern: String,
    handler: EventHandler,
}

/// Synchronous pub/sub event bus with handler dispatch and event history.
pub struct DefaultEventBus {
    /// Pending events queue
    queue: Mutex<Vec<Event>>,
    /// Active subscriptions
    subscriptions: Mutex<Vec<Subscription>>,
    /// Event history (ring buffer)
    history: Mutex<Vec<Event>>,
    /// Max history size
    max_history: usize,
}

impl DefaultEventBus {
    /// Create a new event bus with default history size.
    pub fn new() -> Self {
        Self {
            queue: Mutex::new(Vec::new()),
            subscriptions: Mutex::new(Vec::new()),
            history: Mutex::new(Vec::new()),
            max_history: 100,
        }
    }

    /// Set the maximum event history size (builder pattern).
    pub fn with_max_history(mut self, max: usize) -> Self {
        self.max_history = max;
        self
    }

    /// Check if a topic matches a pattern
    /// Supports: exact match, prefix with "*" (e.g., "sensor.*" matches "sensor.temp")
    fn topic_matches(pattern: &str, topic: &str) -> bool {
        if pattern == "*" {
            return true;
        }
        if let Some(prefix) = pattern.strip_suffix(".*") {
            return topic.starts_with(prefix);
        }
        if let Some(prefix) = pattern.strip_suffix('*') {
            return topic.starts_with(prefix);
        }
        pattern == topic
    }
}

impl Default for DefaultEventBus {
    fn default() -> Self { Self::new() }
}

impl EventBus for DefaultEventBus {
    fn publish(&self, event: Event) -> Result<()> {
        debug!(topic = %event.topic, source = %event.source, "Event published");
        let mut queue = self.queue.lock()
            .unwrap_or_else(|e| { tracing::warn!("Queue mutex poisoned, recovering"); e.into_inner() });
        queue.push(event);
        Ok(())
    }

    fn subscribe(&self, topic_pattern: &str, handler: EventHandler) -> Result<String> {
        let id = uuid::Uuid::new_v4().to_string();
        let sub = Subscription {
            id: id.clone(),
            pattern: topic_pattern.to_string(),
            handler,
        };

        let mut subs = self.subscriptions.lock()
            .unwrap_or_else(|e| { tracing::warn!("Subscriptions mutex poisoned, recovering"); e.into_inner() });
        subs.push(sub);

        debug!(pattern = %topic_pattern, id = %&id[..8], "Subscribed to events");
        Ok(id)
    }

    fn unsubscribe(&self, subscription_id: &str) -> Result<bool> {
        let mut subs = self.subscriptions.lock()
            .unwrap_or_else(|e| { tracing::warn!("Subscriptions mutex poisoned, recovering"); e.into_inner() });
        let len_before = subs.len();
        subs.retain(|s| s.id != subscription_id);
        Ok(subs.len() < len_before)
    }

    fn pending_count(&self) -> usize {
        self.queue.lock()
            .unwrap_or_else(|e| e.into_inner())
            .len()
    }

    fn drain(&self) -> Result<usize> {
        // Take all pending events
        let events: Vec<Event> = {
            let mut queue = self.queue.lock()
                .unwrap_or_else(|e| { tracing::warn!("Queue mutex poisoned, recovering"); e.into_inner() });
            std::mem::take(&mut *queue)
        };

        let count = events.len();
        if count == 0 {
            return Ok(0);
        }

        debug!(count = count, "Draining events");

        // Collect new events generated by handlers
        let mut new_events: Vec<Event> = Vec::new();

        let subs = self.subscriptions.lock()
            .unwrap_or_else(|e| { tracing::warn!("Subscriptions mutex poisoned, recovering"); e.into_inner() });

        for event in &events {
            for sub in subs.iter() {
                if Self::topic_matches(&sub.pattern, &event.topic)
                    && let Some(response_event) = (sub.handler)(event)
                {
                    new_events.push(response_event);
                }
            }
        }

        // Add to history
        {
            let mut history = self.history.lock()
                .unwrap_or_else(|e| { tracing::warn!("History mutex poisoned, recovering"); e.into_inner() });
            for event in events {
                history.push(event);
            }
            // Trim history to max size
            while history.len() > self.max_history {
                history.remove(0);
            }
        }

        // Publish any response events (from handlers)
        // Drop subs lock first to avoid deadlock
        drop(subs);
        for new_event in new_events {
            self.publish(new_event)?;
        }

        Ok(count)
    }

    fn recent_events(&self, limit: usize) -> Result<Vec<Event>> {
        let history = self.history.lock()
            .unwrap_or_else(|e| { tracing::warn!("History mutex poisoned, recovering"); e.into_inner() });
        let start = if history.len() > limit { history.len() - limit } else { 0 };
        Ok(history[start..].to_vec())
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::sync::Arc;
    use std::sync::atomic::{AtomicUsize, Ordering};

    #[test]
    fn test_publish_and_drain() {
        let bus = DefaultEventBus::new();
        bus.publish(Event::new("test.topic", "test")).unwrap();
        bus.publish(Event::new("test.topic", "test")).unwrap();

        assert_eq!(bus.pending_count(), 2);
        let drained = bus.drain().unwrap();
        assert_eq!(drained, 2);
        assert_eq!(bus.pending_count(), 0);
    }

    #[test]
    fn test_subscribe_and_handle() {
        let bus = DefaultEventBus::new();
        let counter = Arc::new(AtomicUsize::new(0));
        let counter_clone = counter.clone();

        bus.subscribe("test.*", Box::new(move |_event| {
            counter_clone.fetch_add(1, Ordering::SeqCst);
            None
        })).unwrap();

        bus.publish(Event::new("test.one", "src")).unwrap();
        bus.publish(Event::new("test.two", "src")).unwrap();
        bus.publish(Event::new("other.topic", "src")).unwrap(); // won't match

        bus.drain().unwrap();
        assert_eq!(counter.load(Ordering::SeqCst), 2);
    }

    #[test]
    fn test_topic_matching() {
        assert!(DefaultEventBus::topic_matches("*", "anything"));
        assert!(DefaultEventBus::topic_matches("sensor.*", "sensor.temp"));
        assert!(DefaultEventBus::topic_matches("sensor.*", "sensor.motion"));
        assert!(!DefaultEventBus::topic_matches("sensor.*", "alert.critical"));
        assert!(DefaultEventBus::topic_matches("sensor.temp", "sensor.temp"));
        assert!(!DefaultEventBus::topic_matches("sensor.temp", "sensor.motion"));
    }

    #[test]
    fn test_handler_generates_response_event() {
        let bus = DefaultEventBus::new();
        let counter = Arc::new(AtomicUsize::new(0));
        let counter_clone = counter.clone();

        // Handler that generates a response event when value exceeds threshold
        bus.subscribe("sensor.*", Box::new(|event| {
            if let Some(value) = event.data.get("value")
                && value.parse::<f64>().unwrap_or(0.0) > 100.0
            {
                return Some(Event::new("alert.threshold", "pipeline")
                    .with_data("device", event.data.get("device").cloned().unwrap_or_default())
                    .with_data("value", value.clone())
                    .with_priority(EventPriority::Critical));
            }
            None
        })).unwrap();

        // Subscribe to alerts
        bus.subscribe("alert.*", Box::new(move |_event| {
            counter_clone.fetch_add(1, Ordering::SeqCst);
            None
        })).unwrap();

        // Publish a high-value sensor event
        bus.publish(
            Event::new("sensor.temperature", "temp-sensor")
                .with_data("device", "device_01")
                .with_data("value", "105.5")
        ).unwrap();

        // First drain: processes sensor event -> generates alert
        bus.drain().unwrap();
        // Second drain: processes the generated alert event
        bus.drain().unwrap();

        assert_eq!(counter.load(Ordering::SeqCst), 1);
    }

    #[test]
    fn test_unsubscribe() {
        let bus = DefaultEventBus::new();
        let counter = Arc::new(AtomicUsize::new(0));
        let counter_clone = counter.clone();

        let sub_id = bus.subscribe("test", Box::new(move |_| {
            counter_clone.fetch_add(1, Ordering::SeqCst);
            None
        })).unwrap();

        bus.publish(Event::new("test", "src")).unwrap();
        bus.drain().unwrap();
        assert_eq!(counter.load(Ordering::SeqCst), 1);

        // Unsubscribe
        assert!(bus.unsubscribe(&sub_id).unwrap());

        bus.publish(Event::new("test", "src")).unwrap();
        bus.drain().unwrap();
        assert_eq!(counter.load(Ordering::SeqCst), 1); // No increase
    }

    #[test]
    fn test_recent_events() {
        let bus = DefaultEventBus::new();
        for i in 0..5 {
            bus.publish(Event::new(format!("topic.{}", i), "src")).unwrap();
        }
        bus.drain().unwrap();

        let recent = bus.recent_events(3).unwrap();
        assert_eq!(recent.len(), 3);
        assert_eq!(recent[0].topic, "topic.2"); // oldest of last 3
        assert_eq!(recent[2].topic, "topic.4"); // newest
    }

    #[test]
    fn test_history_ring_buffer() {
        let bus = DefaultEventBus::new().with_max_history(3);
        for i in 0..10 {
            bus.publish(Event::new(format!("t.{}", i), "src")).unwrap();
        }
        bus.drain().unwrap();

        let recent = bus.recent_events(10).unwrap();
        assert_eq!(recent.len(), 3); // Only last 3 kept
    }

    #[test]
    fn test_wildcard_all() {
        let bus = DefaultEventBus::new();
        let counter = Arc::new(AtomicUsize::new(0));
        let c = counter.clone();

        bus.subscribe("*", Box::new(move |_| { c.fetch_add(1, Ordering::SeqCst); None })).unwrap();

        bus.publish(Event::new("any.topic.here", "src")).unwrap();
        bus.publish(Event::new("another", "src")).unwrap();
        bus.drain().unwrap();

        assert_eq!(counter.load(Ordering::SeqCst), 2);
    }
}
